---
abstract: 'API para enviar SMS através da NSMS (http://www.nsms.com.br/)'
author:
  - 'Thiago Rondon <thiago@nsms.com.br>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NSMS-API
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  URI::Escape: 0
  utf8: 0
resources:
  bugtracker: http://github.com/maluco/NSMS-API/issues
  repository: git://github.com/maluco/NSMS-API.git
version: 0.006
